name: "Terraform Pipeline"

on:
  push:
    branches:
      - main
      - feature/pipeline

env:
  TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Nomes dos arquivos de plano
  PLAN_VPC: "tfplan-vpc"
  PLAN_IGW: "tfplan-igw"
  PLAN_SG: "tfplan-sg"

jobs:
  # VPC Module
  vpc:
    name: "VPC Module"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Init (VPC)
        run: terraform init

      - name: Terraform Plan (VPC)
        run: terraform plan -target=module.vpc -out=${{ env.PLAN_VPC }}

      - name: Save Terraform Artifacts (VPC)
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-vpc
          path: .

      - name: Terraform Apply (VPC)
        run: terraform apply -auto-approve ${{ env.PLAN_VPC }}

  # Internet Gateway Module
  internet-gateway:
    name: "IGW Module"
    needs: vpc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Init (IGW)
        run: terraform init

      - name: Terraform Plan (IGW)
        run: terraform plan -target=module.internet_gateway -out=${{ env.PLAN_IGW }}

      - name: Save Terraform Artifacts (IGW)
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-igw
          path: .

      - name: Terraform Apply (IGW)
        run: terraform apply -auto-approve ${{ env.PLAN_IGW }}

  # Security Group Module
  security-group:
    name: "SG Module"
    needs: internet-gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Init (SG)
        run: terraform init

      - name: Terraform Plan (SG)
        run: terraform plan -target=module.security_group -out=${{ env.PLAN_SG }}

      - name: Save Terraform Artifacts (SG)
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-sg
          path: .

      - name: Terraform Apply (SG)
        run: terraform apply -auto-approve ${{ env.PLAN_SG }}

  # Cleanup on Failure
  cleanup:
    name: "Terraform Destroy on Failure"
    if: failure()  # Executa apenas se algum job falhar
    needs: [vpc, internet-gateway, security-group]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Baixar todos os artefatos de uma só vez
      - name: Download All Terraform Artifacts
        uses: actions/download-artifact@v3
        with:
          name: "*"
          path: .

      # Destruir recursos relacionados aos Security Groups
      - name: Terraform Destroy Security Group
        run: cd artifacts-sg && terraform destroy -auto-approve -target=module.security_group

      # Destruir recursos relacionados ao Internet Gateway
      - name: Terraform Destroy Internet Gateway
        run: cd artifacts-igw && terraform destroy -auto-approve -target=module.internet_gateway

      # Destruir a VPC
      - name: Terraform Destroy VPC
        run: cd artifacts-vpc && terraform destroy -auto-approve -target=module.vpc